baseURL = "https://maxturgeon.ca/f21-stat3150/"
languageCode = "en-ca"
title = "STAT 3150 - Fall 2021"
theme = "book"
ignoreFiles = ["_files$", "_cache$"]

[params]
BookMenuBundle = "/menu"
BookToC = false
BookSearch = false
